// Author: Jon Maken, All Rights Reserved
// License: 3-clause BSD

package env

var BatWrapper = `@echo off
rem autogenerated by uru

set URU_INVOKER=batch

"%~dp0uru_rt.exe" %*

if "x%URU_HOME%x"=="xx" (
  if exist "%USERPROFILE%\.uru\uru_lackee.bat" (call "%USERPROFILE%\.uru\uru_lackee.bat")
) else (
  if exist "%URU_HOME%\uru_lackee.bat" (call "%URU_HOME%\uru_lackee.bat")
)
`

var PSWrapper = `# autogenerated by uru

$env:URU_INVOKER = 'powershell'

uru_rt.exe $args

if ($env:URU_HOME) {
  if(Test-Path "$env:URU_HOME\uru_lackee.ps1"){ & $env:URU_HOME\uru_lackee.ps1 }
} else {
  if(Test-Path "$env:USERPROFILE\.uru\uru_lackee.ps1"){ & $env:USERPROFILE\.uru\uru_lackee.ps1 }
}
`
